name: Auto Post Singapore Result

on:
  schedule:
    - cron: '40 10 * * *'  # Jam 17:40 WIB (10:40 UTC)
  workflow_dispatch:

jobs:
  auto-post-singapore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Singapore result script
        env:
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_API_URL: ${{ secrets.WP_API_URL }}
        run: |
          python run.py
